### ISSUE TITLE
Remove the service recipe from slides

### ISSUE THREAD

**Issue by brucecoddington** [improving-minnesota/angular-training#136]
I think we need to remove the section on 'service' as the factory method, since the Angular docs don't even include it anymore. Just concentrate on Providers and Factories

**Comment by brucecoddington** [comment]
errrr...or..maybe..not

**Comment by mrkelly** [comment]
Well, I've never seen anyone actually use it so maybe it would be good to remove.

**Comment by brucecoddington** [comment]
closing.
